//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadaBookS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public Nullable<int> Book_id { get; set; }
        public string user_email { get; set; }
        public string o_BookName { get; set; }
        public string price { get; set; }
        public string day { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public string End_date { get; set; }
    }
}
